apiVersion: v1
kind: ReplicationController
metadata:
     name: myhttpbin-rc
spec:
  replicas: 2
  selector:
     app: myhttpbin-rc
     
  template:
    metadata:
      labels:
        app: myhttpbin-rc
        
    spec:
      containers:
        - name: httpbin-container
          image: smrutipriya/httpbin
          ports:
            - containerPort: 80

  