apiVersion: v1
kind: Service
metadata:
  name: myhttpbin-svc
  labels:
     app: myhttpbin
    
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
      app:  httpbin
     